name: example_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ^3.7.2

dependencies:
  authentication:
    path: ../../feature/authentication
  dependency_injection:
    path: ../../utility/dependency_injection
  design_system:
    path: ../../utility/design_system
  domain:
    path: ../../package/domain
  event_bus:
    path: ../../utility/event_bus
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0
  storage:
    path: ../../utility/storage
  user_state:
    path: ../../package/user_state

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  linting:
    path: ../../utility/linting
  mobx_codegen: ^2.7.0


flutter:
  uses-material-design: true
