name: storage
description: "A new Flutter package project."
version: 0.0.2
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  linting:
    path: ../../utility/linting

dependency_overrides:
  flutter_lints: ^5.0.0