name: flutter_monorepo_example

packages:
  - app/**
  - feature/**
  - package/**
  - utility/**

scripts:
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `flutter analyze` in all packages.
    
  format:
    run: melos exec -- dart format . --set-exit-if-changed
    description: Run `dart format` in all packages.
    
  test:
    run: melos exec -- flutter test
    description: Run `flutter test` in all packages.

  codegen:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    description: Run `build_runner` to generate code in all packages.