name: authentication
description: A Flutter package for authentication features.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dependency_injection:
    path: ../../utility/dependency_injection
  design_system:
    path: ../../utility/design_system
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  json_annotation: ^4.9.0
  mobx: ^2.5.0
  storage:
    path: ../../utility/storage


dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  linting:
    path: ../../utility/linting
  mobx_codegen: ^2.7.0


