name: user_state
description: "A Flutter package for managing user state in applications."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  dependency_injection:
    path: ../../utility/dependency_injection
  domain:
    path: ../../package/domain
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  storage:
    path: ../../utility/storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  linting:
    path: ../../utility/linting